---
- name: Install and Run Exploit for CVE-2018-20062
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

